FROM node:latest
COPY . ./
RUN npm install 
RUN npm install -g serve
RUN npm run build
RUN useradd -m app
RUN chown -R app dist 
ENV API_URL http://localhost:8000
CMD ["npm", "start"]
USER app
EXPOSE 5000
